# Generated by Django 5.1 on 2024-11-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='file',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='submission',
            name='time_taken',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
