# Generated by Django 5.1 on 2024-11-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='submission',
            name='time_taken',
            field=models.FloatField(default=0),
        ),
    ]
