# Generated by Django 5.1 on 2024-12-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='file',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='llm_model',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='entry',
        ),
    ]
