# Generated by Django 5.1 on 2024-09-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='submission_num',
            field=models.IntegerField(default=10),
        ),
    ]
