# Generated by Django 5.1 on 2024-09-15 13:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_model', models.CharField(choices=[('bert-base', 'BERT Base'), ('bert-large', 'BERT Large')], max_length=20)),
                ('file', models.FileField(upload_to='submission_chat/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('llm_model', models.CharField(choices=[('bert-base', 'BERT Base'), ('bert-large', 'BERT Large')], max_length=20)),
                ('file', models.FileField(upload_to='submission_files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
