# Generated by Django 5.1 on 2024-09-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_submissionchat_submissionfile_delete_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionchat',
            name='file',
        ),
        migrations.RemoveField(
            model_name='submissionchat',
            name='llm_model',
        ),
        migrations.AddField(
            model_name='submissionchat',
            name='chat',
            field=models.JSONField(default=[]),
        ),
    ]
