# Generated by Django 5.1.1 on 2024-09-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_submissionchat_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionchat',
            name='chat',
            field=models.JSONField(default=list),
        ),
    ]
